name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: alerts_frame_win_test.py
        type: choice
        options:
          - alerts_frame_win_test.py
          - element_test.py
          - form_test.py
          - one test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run alerts_frame_win_test.py
        if: "github.event.inputs.deployment_target == 'alerts_frame_win_test.py'"
        run: pytest tests/alerts_frame_win_test.py
      - name: Run element_test.py
        if: "github.event.inputs.deployment_target == 'element_test.py'"
        run: pytest tests/element_test.py
      - name: Run form_test.py
        if: "github.event.inputs.deployment_target == 'form_test.py'"
        run: pytest tests/form_test.py
      - name: Run form_test.py
        if: "github.event.inputs.deployment_target == 'one test'"
        run: pytest tests/alerts_frame_win_test.py::test_new_tab
